name: "Build and deploy to nuget.org"

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    name: "Deploy"
    runs-on: windows-latest
    steps:
      - uses: Fedodo/Fedodo.Pipelines/BuildAndDeployNuGet@main
        with:
          PROJECT_PATH: "Fedodo.NuGet.Common/Fedodo.NuGet.Common.csproj"
          NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"
          VERSION: 1.0.${{ github.run_number }}
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
          PACKAGE_OUTPUT_DIRECTORY: "${{ github.workspace }}\output"